### ISSUE TITLE
Reading in kineticLaws that contain other reactions (case1231)

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#138]
## Minimal code example to reproduce the problem

```Julia
case = "01231"
url = "https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/master/cases/semantic/$case/$case-sbml-l3v2.xml"
tmpfile = download(url)
try
    SBMLToolkit.checksupport(tmpfile)
    ml = readSBML(tmpfile, doc -> begin
            set_level_and_version(3, 2)(doc)
            convert_simplify_math(doc)
        end)
    println(ml.reactions["J0"].kinetic_math)
finally
    rm(tmpfile)
end
```

## Expected behavior

Judging from the true time course of this case the reaction "J0" should be substituted with its kineticLaw "k1". What should be printed is `SBML.MathApply("+", SBML.MathIdent("k1"), SBML.MathVal{Int32}(1)])`

## Actual behavior

prints `SBML.MathApply("+", SBML.Math[SBML.MathIdent("J0"), SBML.MathVal{Int32}(1)])`

**Comment by exaexa** [comment]
this is a math interpretation issue; the substitution there actually changes the underlying SBML semantics (suddenly the rate information skips one dependency, and behaves differently upon model modifications). This should not be fixed in SBML.jl, perhaps only if there's some libsbml switch for `convert_simplify_math` that would add this.

BTW this isn't done automatically by symbolics/mtk? I'd hope that if you enter a primitive rule like `J0=k1` into whatever advanced math system, it just unifies the variables right away.

**Comment by paulflang** [comment]
> the substitution there actually changes the underlying SBML semantics (suddenly the rate information skips one dependency, and behaves differently upon model modifications).

What do you mean with that?

> BTW this isn't done automatically by symbolics/mtk? I'd hope that if you enter a primitive rule like J0=k1 into whatever advanced math system, it just unifies the variables right away.

I was about to write the substitution operating on the rate_rule in its Symbolics form in SBMLToolkit.jl. But than I thought this should be handled as far downstream in the conversion as possible, so I created the issue here. Should perhaps created it for libSBML, though.

**Comment by exaexa** [comment]
> semantic change

this is probably not the case with a single reaction only, but in multiple reaction systems the automatic substitution basically breaks links between stuff, thus loses information.

> as far downstream in the conversion as possible

This is is a very specific change, I guess that actually substituing the rest of the stuff in SBMLToolkit would make most sense. If this makes sense also for other usecases, it should be supported by libsbml as a model conversion function.

I'm closing this as wontfix because I think we really can't do much directly in SBML.jl without introducing application bias. I kindof wonder we could eventually separate this whole math logic into a separate package that could reasonably reimplement all the substitutions, lambdas, and all other stuff.
