### ISSUE TITLE
new jll with experimental builds (m1)

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#152]
currently to use SBML with m1, you need https://github.com/giordano/SBML_jll.jl/

this is just a tracker that when the next version of libSBML is tagged, it'd be nice to change the build script.

right now its a little annoying making PRs and edits because every time I manually add Mose's then remove it before making a PR.

its not a big deal but might be good to have it documented somewhere (outside slack)

**Comment by exaexa** [comment]
For yggdrassil reasons need to wait until either SBML pushes a version bump or something very serious happens (aarch64 gets out of experimental or so).

Technically, is there any reason that would prevent patching the SBML_jll in yggdrasil right now, so that we don't forget about adding the aarch64 build later?

(cc @giordano )

**Comment by exaexa** [comment]
PS. what's the "annoying manual work" ? I guess it shouldn't be hard to make the existence of the extra SBML_jll transparent for your system, if you can please show the precise problem here.

**Comment by exaexa** [comment]
/me waiting for the yearly new release of libsbml like
![image](https://user-images.githubusercontent.com/271543/141262869-e7b62468-8c2d-4313-9ee9-46e5e38fba99.png)

**Comment by anandijain** [comment]
HAHAHA i was thinking the same yesterday 😆
