### ISSUE TITLE
readSBML extension

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/SBML.jl#22]
Hi, I'm in the early stages of building a Julia version of the CobraTool box, see [here](https://github.com/stelmo/CobraTools.jl) for reference. For this I need an SBML reader/writer, and hence my interest in this package. In my package I essentially adopt the COBRApy framework of storing a model as an array of genes, metabolites and reactions. For each of these I aim to import most of the data contained in the model source file, e.g. for metabolites this includes (per metabolite):

1. id
2. name
3. compartment
4. formula
5. charge
6. notes
7. annotations

This is documented in the `Model structure` section of the documentation of CobraTools.jl if you are interested (although the docs are a work in progress).

Currently in SBML.jl only the first three fields from the model source file are being imported. I have forked the package and added some more fields to make SBML.jl mesh better with my package (currently only for species/metabolites). Would you mind looking at the modifications on my fork and letting me know if you would be open to pulling them onto SBML.jl (once I've extended the genes and reactions, and added some tests of course)?

**Comment by exaexa** [comment]
If it's extractable using the libSBML C interface it should not be a problem. I'll eventually have a look at it, probably together with SBML writing (see the other issue. :] ).

**Comment by exaexa** [comment]
@stelmo Just checking-- do the following API functions look like they would extract the information you want?

- formula: http://sbml.org/Software/libSBML/docs/c-api/class_fbc_species_plugin__t.html#afeae84e56f964906a018bc05d4bad2b7
- charge: http://sbml.org/Software/libSBML/docs/c-api/class_fbc_species_plugin__t.html#ae19c4ab9ea611f987379e9ac7d168349
- notes: http://sbml.org/Software/libSBML/docs/c-api/class_s_base__t.html#a54e7454feeb46c70decb0c0275140677 (is it better to get the notes as a parsed XML/HTML or just as a string? I'd prefer strings since the field is basically free-form.)
- annotations: http://sbml.org/Software/libSBML/docs/c-api/class_s_base__t.html#a465051fdcd07881af6dc6ddb3644ac99 (same as above: X(HT)ML or string?)

**Comment by stelmo** [comment]
Hi @exaexa, yep, those are exactly the ones I used, check out the `temp.jl` file I made [here](https://github.com/stelmo/SBML.jl/blob/cfa4b482067fd54d81fb67e26c8f67e02e822e53/temp.jl) that uses them. The only difficulty I currently have is importing the gene reaction rules. My problem is that I am not sure how to access the struct that contains them. I am basing my workflow on the sbml import script from cobrapy and they recursively cycle through association structs that I am unable to `get` using the C api (I'm not sure which function to call after line 145 in `temp.jl`.

**Comment by exaexa** [comment]
ah nice, thanks. That looks like a mere technical problem (though an ugly one.)

Can I re-use parts of the code? (most importantly, is the license there portable to ours apache2.0?)

**Comment by stelmo** [comment]
So I just checked and they use GNU General Public License v2.0, I'm not sure how that affects your license. However, the stuff I have isn't really verbatim copy, I just used it to figure out which functions to call, so I doubt it would be a problem if you used my code :)

**Comment by exaexa** [comment]
So anyway, it seems there are 2 kinds of annotations:
- freestyle annotation (how's that even different from notes?! :D )  http://sbml.org/Software/libSBML/docs/c-api/class_s_base__t.html#a465051fdcd07881af6dc6ddb3644ac99
- CV terms annotation, likely much more reliable. http://sbml.org/Software/libSBML/docs/c-api/class_s_base__t.html#a27bfc1772a3f7569d5f801702bc7b948
I guess these should be extracted separately, is that right?

**Comment by exaexa** [comment]
@stelmo just checking -- as far as I get it, the "gene product association" is just a boolean formula that contains gene IDs as atoms, right?

**Comment by stelmo** [comment]
Yes! Here is an example from an e coli model: (b0463 and b0462 and b3035) or (b0463 and b2470 and b3035). So essentially every enzyme inside a parenthesis (and) is required for the respective parenthesis block to function, but only one parenthesis block is required (or) for the gene to function. As far as I've seen this is the standard way of representing these types of gene reaction rules. I think they have a standard way of denoting "or" and "and" in SBML. In json/matlab formats its a bit more like the wild west where people use "or", "OR", "|", and "||" in different models. In CobraTools.jl I just use a regex to sort this out..

**Comment by exaexa** [comment]
I guess I can't expect it to be in any kind of normal form like CNF right? :D

**Comment by exaexa** [comment]
ok well, seems like they simply don't have a C API to access that. :D

**Comment by stelmo** [comment]
There is no C api access to the gene reaction rule objects from SBML?

**Comment by exaexa** [comment]
It seems to me that the functions are really missing. I opened this:
https://github.com/sbmlteam/libsbml/issues/130
so we'll see.

Missing stuff now:
- CV terms (I'll probably close this open a separate issue for them, because there's some more considerations)
- gene associations (we'll wait how libsbml team reacts)
otherwise I guess your list is kindof complete now, can you confirm? :]

**Comment by stelmo** [comment]
Yep, my list is complete :)
