### ISSUE TITLE
readSBML fails on SBML semantic test case 00928

### ISSUE THREAD

**Issue by sebapersson** [LCSB-BioCore/SBML.jl#254]
## Minimal code example to reproduce the problem

```julia
using SBML
using Downloads
path = Downloads.download("https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/release/cases/semantic/00928/00928-sbml-l3v2.xml", joinpath(@__DIR__, "model.xml"))
readSBML(path)

path = Downloads.download("https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/release/cases/semantic/00929/00929-sbml-l3v2.xml", joinpath(@__DIR__, "model.xml"))
readSBML(path)
```

## Expected behavior

An SBML.model should be returned.

## Actual behavior

I received the following error message:

```julia
ERROR: ArgumentError: cannot convert NULL to string
Stacktrace:
 [1] unsafe_string
   @ ./strings/string.jl:84 [inlined]
 [2] unsafe_string
   @ ./c.jl:193 [inlined]
 [3] get_model(mdl::Ptr{Nothing})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:666
 [4] _readSBML(symbol::Symbol, fn::String, sbml_conversion::SBML.var"#69#71", report_severities::Vector{String}, throw_severities::Vector{String})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:191
 [5] readSBML(fn::String, sbml_conversion::Function; report_severities::Vector{String}, throw_severities::Vector{String})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:229
 [6] readSBML(fn::String, sbml_conversion::Function)
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:222
 [7] readSBML(fn::String)
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:222
 [8] top-level scope
   @ ~/.julia/dev/PEtab/test/Boehm.jl:221
```

## Optional: Suggestions for fixing

My PEtab importer [PEtab.jl](https://github.com/sebapersson/PEtab.jl) has a SBML importer for ODE models. I am currently working through the [SBML test suite](https://github.com/sbmlteam/sbml-test-suite/tree/release/cases/semantic), and for cases with EventT0Firing (case 928 and 929) I receive the above error message. 

Besides this SBML.jl has worked great, and thanks for creating a SBML importer in Julia! :)

**Comment by exaexa** [comment]
@sebapersson thanks for the report! It looks like we misinterpreted the SBML spec, assuming that the events have to be uniquely identified using the SBML `SId` while in fact the L3V2r2 spec §4.12.1 clearly says that it's not a requirement. The fix is easy, we will need to modify the SBML.jl data structure to reflect the actual spec.

The problem is precisely here:
- https://github.com/LCSB-BioCore/SBML.jl/blob/master/src/structs.jl#L474 (ID is mandated)

I suggest we change:
- `events` field to either `Vector{Event}` or `Vector{Pair{Maybe{String}, Event}}` (behaves more like the current `Dict` for iteration so it should hopefully break less code
- if we choose the simpler variant above, add extra `id::Maybe{String}` into `struct Event`

cc @anandijain @paulflang  -- any comments on this welcome (esp. regarding the backwards compatibility)

**Comment by paulflang** [comment]
Thanks for cc'ing me, @exaexa . I just checked and SBMLtk does not make use of the key. So do what you prefer.
