### ISSUE TITLE
Rate rules 

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#53]
> Rules are currently not imported into SBML.Model (and also not representable as ReactionSystem, I think). Should be imported into SBML.Model at some point to allow lowering to ODESystem.

cc @paulflang  

There are a big class of ODE SBML models that use these Rate laws, so it'd be good to get this in motion.

**Comment by paulflang** [comment]
essentially what we need to import are the things in the SBML `listOfRules`.

**Comment by exaexa** [comment]
Hi! As always, is there some example xml of that available publicly?

**Comment by paulflang** [comment]
example: https://github.com/sbmlteam/sbml-test-suite/blob/master/cases/semantic/00029/00029-sbml-l3v2.xml

If rules are implemented, we can get rid of this: https://github.com/paulflang/SBML.jl/blob/d714fb5014213744ba76f1a1b4cdb74b30689f8b/src/readsbml.jl#L178

**Comment by paulflang** [comment]
I actually run into the issue that models with `Events` are not simulated correctly. I'd like to raise an not implemented error for that, but `Rules` are not represented in `SBML.Model`. Could you represent them? More generally, could you represent everything that is in `listOf___`. The only things that are still missing are (see p. 36 of the SBML specs)

- listOfInitialAssignments
- listOfRules
- listOfConstraints
- listOfEvents

**Comment by paulflang** [comment]
Just to clarify, in my opinion SBML.Model should have a representation of all the `listOf___` attributes that are on [p36 of the specs](http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf).

**Comment by exaexa** [comment]
The `listOf*` is actually a complete antipattern, even in XML. Why would you want it?

**Comment by paulflang** [comment]
To not simulate models incorrectly. I mean what is the antipattern here? We already have most of the listOf* stuff implemented:
- Compartments
- Species
- Reactions

Why not also implement Rules, Events, etc.?

For instance, ignoring the `Rules` in a model that contains them seems to be equivalent to ignoring some reactions at random in a model that contains only reactions (although, I've seen StackOverflow errors in models that contain rules, so at least they don't silently simulate incorrectly. But idk if that is the case for all models where we ignore the rules).

**Comment by exaexa** [comment]
aaaaaaah you actually sounded like reimplementing the listOf* mechanics, that would be bad. Certainly we want all that stuff represented.

Can we _focus_ on single ones at time though? :D

Re rate rules, they may be connected to to:
- species
- compartments
- stoichiometries (aka species references)
- parameters
(so all these structures should have some...do we want them "in" the structure, or externalized?)

Each rate rule contains:
- math
- the name of the variable it affects

Some flagging (or a completely different structure) might be needed for assignment rules and scalar rules (I'm not sure how that works, seems super complicated). Any idea on how to structure that best?

**Comment by paulflang** [comment]
Sorry for the confusion.

I think it is best to discuss with @giordano or Sarah how to structure these so that we don't accumulate technical debt.

I haven't had a close look at the specs, but my gut feeling is that they should be separate types. Perhaps with the exception if they can be represented as Dict, like we have done for Parameters.

**Comment by exaexa** [comment]
Do you have any biomodels with rules handy?

I found a simple one with `algebraicRule` here, looks good to me (species ain't chemicals anymore, yay):  https://www.ebi.ac.uk/biomodels/MODEL1202270000#Files

**Comment by paulflang** [comment]
00029 contains an assignment rule iirc. But it is a test suite model.
I have the test suite downloaded and just grep for the term I am interested in.

**Comment by exaexa** [comment]
a good, the testsuite seems to work

**Comment by isaacsas** [comment]
I haven't read the whole thread, so my apologies if this is already answered. Are rules just algebraic formulas (so you get DAEs)?

We can add a field to ReactionSystems to include constraints (or "rules"), and then pass them onto ODESystems / SDESystems if needed. They won't work for jumps, but that is a broader issue since there are now jump-algebraic equation solvers currently.

**Comment by isaacsas** [comment]
(I think it does make sense to include such info in ReactionSystems.)

**Comment by paulflang** [comment]
Rules can come in multiple flavours:

- Algebraic Rules (I think they are what you meant with "constraints". Note however, that SBML can contain `Constraints`, which are used to define when a simulation reaches a state where it is no longer valid)
- RateRules (I think they describe rate of change of compartments, parameters, species that don't participate in reactions, etc.)
- AssignmentRules (reads a bit like an AlgebraicRule with the requirement that one variable is isolated on the left side, but I might be wrong)

I am in favour of (some of) these being handled by `ReactionSystem`. Not essentially because I believe they belong there, but rather because it allows to read in all SBML models the same way (as opposed some being only read in via `ODEsystem(readSBML(filename))`). However, based on that argumentation, we should also read in `Events` and `Constraints` to `ReactionSystem`.

A more detailed description on Rules can be found on p59 of the [specs](http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf).

**Comment by isaacsas** [comment]
Ok, at the minimum we can add algebraic equations to ReactionSystems. Some of the others may be planned as general ModelingToolkit functionality, so it would make sense for us to adopt them once the interface is standardized.

**Comment by paulflang** [comment]
Actually, on second thought, if AlgebraicRules and AssignmentRules can never be simulated as `JumpSystems`, why support them in ReactionSystem? We could support them in `ODE` and `SDESystem` only. RateRules would be supported there naturally anyway. What are the plans for Events and Constraints? Some sort of `simulation_info` field in all `*System` types that is passed on through all conversion steps?

**Comment by isaacsas** [comment]
They help with allowing composability of ReactionSystems, so I was planning to add them anyways. At some point we can hopefully get them working with jumps too. 

I don’t know where the constraint and event planning is at, maybe @Chrisrackauckas can speak to them.

**Comment by ChrisRackauckas** [comment]
Events are just a form of equation. I'll get to it.

**Comment by anandijain** [comment]
Events just got merged https://github.com/SciML/ModelingToolkit.jl/pull/1337 so soon we can start to actually do this

**Comment by exaexa** [comment]
I think this is completely finished by #170 (Thanks Mose!!) so closing. If extra features are required please open separate feature requests.

:snowman_with_snow:
