### ISSUE TITLE
Handling of lb, ub and oc in `Reaction`s

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#85]
https://github.com/LCSB-BioCore/SBML.jl/blob/3cecd7c3da9d72b3c71ed4733e67f4e56b26d923/src/structs.jl#L131

`Reaction.lb`, `ub`, and `oc` are concepts that are not relevant for barebones (non-fbc) SBML models. Previously, these fields could hold `nothing`. Now I am using, e.g. `(NaN, "")`. I guess this is OK for now, but in the long run it would be good to come up with an idea of how to represent barebones SBML and potentially additional SBML packages. What do you think @exaexa and @giordano ?

**Comment by exaexa** [comment]
This is planned (I already commented on that), thanks for raising it :]

Currently lb/ub are collected from several possible places because of historical simplicity reasons™. The correct way is to pick the Fbc bounds and Parameters into Julia structures and change `getLBs/getUBs` to pick it from there. That should also add a few other features that might be relevant later.

**Comment by giordano** [comment]
Copying here a question from https://github.com/LCSB-BioCore/SBML.jl/issues/121#issuecomment-881529467 since it may be relevant with regard to lb and ub:

> While we're here, should `lb` and `ub` be `Number`s (product of value and units)?

**Comment by exaexa** [comment]
Depends.

If we take it from Fbc, there it's (afaik) unitless. If taken from parameters, the parameters _should_ have units, so these should be Numbers.

Honestly the original idea with separate `lb/ub` is bad now. I'll have a look at it asap.

**Comment by exaexa** [comment]
This is fixed by #162
